title: Ryan Cabell
email: cabell.ryan@gmail.com
description: Software Developer
github_username: rkcabell
search: true
search_full_content: true
logo: #""
repository: "rkcabell/rkcabell.github.io"



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Ryan"
  bio    : "Jack of all, master of **none**"
  location: "Greensboro, NC, USA"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ryan-cabell-7548b5158/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rkcabell"
    #- label: "Example"
    #  icon: "fab fa-fw fa-example"
    #  url: "https://example.com/"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ryan-cabell-7548b5158/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rkcabell"
    #- label: "Instagram"
    #  icon: "fab fa-fw fa-instagram"
    #  url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/